defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: True
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment
env:
  num_envs: 1024 # Number of drones for training
  max_episode_length: 2200
  env_spacing: 8.0 
  num_obstacles: 350

env_dyn:
  num_obstacles: 0 # set to zero if static env is needed
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

viewer:
  eye: [0., 40., 40.]
  lookat: [0., 2.5, 0.]
  resolution: [960, 720]

wandb:
  project: NavRL
  name: static_target_center
  entity: mistletoe235
  mode: online
  run_id: #kw9xf9k9
